# contracts/errors.py
# Eccezioni tipizzate per pipeline trading (no fallback impliciti)

class RMError(Exception): ...
class ConfigError(RMError): ...
class NotReadyError(RMError): ...
class DataStaleError(RMError): ...
class InconsistentStateError(RMError): ...
class ExternalServiceError(RMError): ...
class SimulationError(RMError): ...
class EngineSubmitError(RMError): ...
class EngineCancelError(RMError): ...
